const users={
"TSOC-0001":{name:"テスト 職員",dept:"北参道 / 管理部",role:"申請利用",perms:["apply"]},
"TSOC-0002":{name:"所属長 テスト",dept:"北参道 / 管理部",role:"承認担当あり",perms:["apply","approve"]},
"TSOC-0003":{name:"管理者 テスト",dept:"北参道 / 管理部",role:"管理権限あり",perms:["apply","approve","process","admin"]}
};let current=null;const $=s=>document.querySelector(s);const content=$("#content");const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)};
const patterns=[{id:"A",name:"基本勤務 9:00-18:00",start:"09:00",end:"18:00",breakMinutes:60},{id:"B",name:"早番 8:30-17:30",start:"08:30",end:"17:30",breakMinutes:60},{id:"C",name:"遅番 10:00-19:00",start:"10:00",end:"19:00",breakMinutes:60}];
$("#loginForm").addEventListener("submit",e=>{e.preventDefault();const id=$("#loginId").value.trim().toUpperCase();if(!users[id]||$("#loginPassword").value!=="test"){toast("職員IDまたはパスワードが違います");return}current={id,...users[id]};$("#loginView").classList.add("hidden");$("#systemView").classList.remove("hidden");$("#headerUser").textContent=current.name;$("#headerRole").textContent=current.role;buildNav();showHome()});
$("#logoutBtn").onclick=()=>{current=null;$("#systemView").classList.add("hidden");$("#loginView").classList.remove("hidden");$("#loginPassword").value="";};
function navBtn(label,fn,key){const b=document.createElement("button");b.textContent=label;b.dataset.key=key;b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");fn()};$("#nav").appendChild(b)}
function section(t){const d=document.createElement("div");d.className="nav-section";d.textContent=t;$("#nav").appendChild(d)}
function buildNav(){const n=$("#nav");n.innerHTML="";navBtn("ホーム",showHome,"home");section("申請");navBtn("新規申請",showNew,"new");navBtn("自分の申請",showMine,"mine");if(current.perms.includes("approve")){section("承認");navBtn("承認待ち",showApproval,"approval")}if(current.perms.includes("process")){section("事務処理");navBtn("処理待ち",()=>placeholder("事務処理待ち","最終承認後の処理対象を確認します。"),"process")}if(current.perms.includes("admin")){section("管理");navBtn("管理画面",showAdmin,"admin")}}
function head(title,sub,action=""){return `<div class="page-head"><div><h1>${title}</h1><div class="muted">${sub}</div></div>${action}</div>`}
function showHome(){content.innerHTML=head("ホーム",`${current.name} さん、お疲れさまです。`)+`<div class="cards"><div class="card metric">申請中<b>1</b></div><div class="card metric">差戻し<b>0</b></div><div class="card metric">${current.perms.includes("approve")?"承認待ち":"完了"}<b>${current.perms.includes("approve")?"2":"3"}</b></div></div><div class="card"><h2>よく使う操作</h2><div class="quick"><button id="qApply"><b>時間外勤務申請</b><span class="muted">新しい申請を作成</span></button><button id="qMine"><b>自分の申請</b><span class="muted">進捗・差戻しを確認</span></button></div></div>`;$("#qApply").onclick=showOvertime;$("#qMine").onclick=showMine}
function showNew(){content.innerHTML=head("新規申請","申請する書類を選択してください。")+`<div class="card"><h2>勤怠</h2><div class="quick"><button id="ot"><b>時間外勤務申請</b><span class="muted">時間外勤務を事前申請</span></button><button disabled title="今後追加"><b>休暇・その他（準備中）</b><span class="muted">今後追加予定</span></button></div></div>`;$("#ot").onclick=showOvertime}
function showMine(){content.innerHTML=head("自分の申請","申請状況と履歴を確認します。")+`<div class="card table-wrap"><table><thead><tr><th>申請番号</th><th>申請書</th><th>勤務日</th><th>状態</th></tr></thead><tbody><tr><td>OT-DEMO-0001</td><td>時間外勤務申請</td><td>2026/10/05</td><td><span class="badge blue">承認中</span></td></tr></tbody></table></div>`}
function showOvertime(){content.innerHTML=head("時間外勤務申請","時間外勤務を行う場合は、事前に申請してください。",'<span class="badge">下書き</span>')+`<div class="notice">届出年月日は「申請する」を押した正式提出時に自動記録します。</div><form id="otForm"><section class="card"><h2>申請者情報</h2><div class="grid3"><label>職員番号<input value="${current.id}" readonly></label><label>所属<input value="${current.dept}" readonly></label><label>氏名<input value="${current.name}" readonly></label></div></section><section class="card"><h2>時間外勤務</h2><div class="grid3"><label>勤務日<input id="workDate" type="date" value="2026-10-05" required></label><label>当日のシフト<select id="workPattern">${patterns.map(p=>`<option value="${p.id}">${p.name}</option>`).join("")}</select><small class="muted">所属部門のシフトのみ表示</small></label><label>所定勤務時間<input id="scheduled" readonly></label><label>所定休憩<input id="scheduledBreak" readonly></label><label>開始時刻<input id="start" type="time" required></label><label>終了時刻<input id="end" type="time" value="19:30" required></label><label>時間外勤務時間<input id="duration" readonly></label></div><label>時間外勤務が必要な理由<textarea id="reason" rows="3" required></textarea></label><label>時間外削減の取組み<textarea id="reduction" rows="2" required></textarea></label><div class="grid2"><fieldset><legend>休憩時間</legend><label class="inline"><input type="radio" name="br" value="なし" checked>なし</label><label class="inline"><input type="radio" name="br" value="あり">あり</label></fieldset><fieldset><legend>深夜勤務予定</legend><label class="inline"><input type="radio" name="late" value="なし" checked>なし</label><label class="inline"><input type="radio" name="late" value="あり">あり</label></fieldset></div></section><section class="card"><h2>この申請の承認経路</h2><p class="muted">現在の所属・役職等のマスター情報から申請前に自動判定します。申請者自身は経路を選択しません。</p><div class="route"><span>1</span><div><b>一次承認</b><small>勤怠担当（サンプル）</small></div><b>→</b><span>2</span><div><b>最終承認</b><small>所属・役職から自動判定（サンプル）</small></div></div><div class="notice" style="margin-top:14px">承認者・経路に誤りがある場合は、申請前に管理者へ確認してください。</div></section><div class="actions"><button type="button" class="secondary" id="draft">下書き保存</button><button type="submit">申請する</button></div></form>`;const apply=()=>{const p=patterns.find(x=>x.id===$("#workPattern").value);$("#scheduled").value=p.start+" ～ "+p.end;$("#scheduledBreak").value=p.breakMinutes+"分";$("#start").value=p.end;calc()};const calc=()=>{const a=$("#start").value,b=$("#end").value;if(!a||!b)return;let [ah,am]=a.split(":").map(Number),[bh,bm]=b.split(":").map(Number),m=bh*60+bm-ah*60-am;if(m<0)m+=1440;$("#duration").value=Math.floor(m/60)+"時間"+m%60+"分"};$("#workPattern").onchange=apply;$("#start").oninput=calc;$("#end").oninput=calc;apply();$("#draft").onclick=()=>toast("下書き保存（テスト）");$("#otForm").onsubmit=e=>{e.preventDefault();toast("申請しました（テスト）");setTimeout(()=>current.perms.includes("approve")?showApproval():showMine(),500)}}
function showApproval(){content.innerHTML=head("承認待ち","あなたの承認が必要な申請です。")+`<div class="card table-wrap"><table><thead><tr><th>申請番号</th><th>申請者</th><th>申請書</th><th>状態</th><th></th></tr></thead><tbody><tr><td>OT-DEMO-0001</td><td>テスト 職員</td><td>時間外勤務申請</td><td><span class="badge blue">承認待ち</span></td><td><button id="review">確認</button></td></tr></tbody></table></div>`;$("#review").onclick=showReview}
function showReview(){content.innerHTML=head("時間外勤務申請の承認","OT-DEMO-0001")+`<div class="card"><h2>申請内容</h2><div class="summary"><b>申請者</b><span>テスト 職員（北参道 / 管理部）</span><b>勤務日</b><span>2026/10/05</span><b>シフト</b><span>基本勤務 9:00-18:00</span><b>時間外勤務</b><span>18:00 ～ 19:30（1時間30分）</span><b>理由</b><span>テスト申請</span></div></div><div class="card"><h2>承認操作</h2><label>コメント<textarea id="comment" rows="3" placeholder="差戻し・却下の場合は必須"></textarea></label><div class="actions"><button class="danger" id="reject">却下</button><button class="secondary" id="return">差戻し</button><button id="approve">承認</button></div></div>`;const act=k=>{if((k==="差戻し"||k==="却下")&&!$("#comment").value.trim()){toast("コメントを入力してください");return}toast(k+"として記録しました（テスト）")};$("#reject").onclick=()=>act("却下");$("#return").onclick=()=>act("差戻し");$("#approve").onclick=()=>act("承認")}
function showAdmin(){content.innerHTML=head("管理","TSOC Staff System のマスター・運用設定を管理します。")+`<div class="admin-grid"><div class="admin-tile"><b>職員管理</b><p class="muted">職員ID、氏名、メール、在籍状態、権限</p><button data-a="職員管理">確認</button></div><div class="admin-tile"><b>拠点・所属</b><p class="muted">拠点に連動した所属を名称で管理</p><button data-a="組織・所属">確認</button></div><div class="admin-tile"><b>職種・役職</b><p class="muted">職種・役職と業務上の担当</p><button data-a="職種・役職">確認</button></div><div class="admin-tile"><b>勤務パターン</b><p class="muted">部門別シフト・所定時間・休憩</p><button id="patternAdmin">確認</button></div><div class="admin-tile"><b>申請書管理</b><p class="muted">申請書の有効化・バージョン</p><button data-a="申請書管理">確認</button></div><div class="admin-tile"><b>承認経路</b><p class="muted">個人・役職・担当グループを組み合わせた経路設定</p><button data-a="承認経路">確認</button></div><div class="admin-tile"><b>完了後処理</b><p class="muted">勤怠・人事等の処理先</p><button data-a="完了後処理">確認</button></div><div class="admin-tile"><b>操作履歴</b><p class="muted">申請・承認・管理変更の監査履歴</p><button data-a="操作履歴">確認</button></div></div>`;document.querySelectorAll("[data-a]").forEach(b=>b.onclick=()=>placeholder(b.dataset.a,"この管理機能は次の確認対象として順次実装します。"));$("#patternAdmin").onclick=showPatternAdmin}
function showPatternAdmin(){content.innerHTML=head("勤務パターン","共通の勤務パターンを作成し、複数所属へ割り当てます。",'<button id="addPattern">＋勤務パターン追加</button>')+`<div class="card table-wrap"><table><thead><tr><th>名称</th><th>利用所属</th><th>所定時間</th><th>休憩</th><th>状態</th></tr></thead><tbody>${patterns.map(p=>`<tr><td>${p.name.split(" ")[0]}</td><td>複数所属に割当可能</td><td>${p.start} ～ ${p.end}</td><td>${p.breakMinutes}分</td><td><span class="badge">有効</span></td></tr>`).join("")}</tbody></table></div>`;$("#addPattern").onclick=()=>toast("追加画面は次版で実装します")}
function placeholder(title,sub){content.innerHTML=head(title,sub)+`<div class="card"><h2>画面確認準備中</h2><p>この機能は、マスター項目と運用方法を確認しながら次の版で実装します。</p><button id="backAdmin" class="secondary">管理画面へ戻る</button></div>`;$("#backAdmin").onclick=showAdmin}
/* v0.3.2 master screens: non-personal master values from the uploaded initial master. Real employee data is intentionally not published. */
const masterSites=[{name:"TSOC北参道",active:true},{name:"TSOC池袋",active:true}];
const masterDepartments=[
{site:"TSOC北参道",name:"リハビリテーション部"},{site:"TSOC北参道",name:"病棟看護部"},{site:"TSOC北参道",name:"手術室看護部"},{site:"TSOC北参道",name:"外来看護部"},{site:"TSOC北参道",name:"放射線部"},{site:"TSOC北参道",name:"外来医事課"},
{site:"TSOC池袋",name:"リハビリテーション部"},{site:"TSOC池袋",name:"外来看護部"},{site:"TSOC池袋",name:"放射線部"},{site:"TSOC池袋",name:"外来医事課"}];
const masterPositions=["理事長","副理事長","事務長","北参道院長","池袋院長","北参道副院長","池袋副院長","センター長","部長","北参道部長","池袋部長","師長","北参道師長","池袋師長"];
const masterJobs=["医師","理学療法士","作業療法士","アスレティックトレーナー","看護師","看護助手","診療放射線技師","臨床工学士","医療事務","総務","中材スタッフ"];
function masterTable(title,items,sub){content.innerHTML=head(title,sub,'<button id="addMaster">＋追加</button>')+`<div class="card table-wrap"><table><thead><tr><th>名称</th><th>状態</th><th></th></tr></thead><tbody>${items.map(x=>`<tr><td>${typeof x==="string"?x:x.name}</td><td><span class="badge">有効</span></td><td><button class="secondary masterEdit">編集</button> <button class="secondary masterUse">使用状況</button></td></tr>`).join("")}</tbody></table></div>`;$("#addMaster").onclick=()=>toast("名称を入力して追加する画面を次段階で保存可能にします");document.querySelectorAll(".masterEdit").forEach(b=>b.onclick=()=>toast("編集画面（テスト）"));document.querySelectorAll(".masterUse").forEach(b=>b.onclick=()=>toast("参照先チェック：使用中なら削除不可"))}
function showAdmin(){content.innerHTML=head("管理","マスターは名称で選択・管理します。内部コードを覚える必要はありません。")+`<div class="admin-grid">
<div class="admin-tile"><b>職員管理</b><p class="muted">氏名、所属、職種、役職、権限</p><button id="staffMaster">確認</button></div>
<div class="admin-tile"><b>拠点</b><p class="muted">TSOC北参道・TSOC池袋</p><button id="siteMaster">確認</button></div>
<div class="admin-tile"><b>所属</b><p class="muted">拠点を選ぶと所属候補を絞り込み</p><button id="deptMaster">確認</button></div>
<div class="admin-tile"><b>役職</b><p class="muted">承認経路で利用する役職・承認階層</p><button id="positionMaster">確認</button></div>
<div class="admin-tile"><b>職種</b><p class="muted">医師・看護師・診療放射線技師など</p><button id="jobMaster">確認</button></div>
<div class="admin-tile"><b>担当グループ</b><p class="muted">医療安全管理者、勤怠担当など</p><button id="groupMaster">確認</button></div>
<div class="admin-tile"><b>勤務パターン</b><p class="muted">共通シフトを複数所属へ割当</p><button id="patternMaster">確認</button></div>
<div class="admin-tile"><b>承認経路</b><p class="muted">個人・役職・担当グループを組合せ</p><button id="routeMaster">確認</button></div></div>`;
$("#staffMaster").onclick=showStaffMaster;$("#siteMaster").onclick=()=>masterTable("拠点",masterSites,"現在入力済みの拠点マスターです。");$("#deptMaster").onclick=showDepartmentMaster;$("#positionMaster").onclick=()=>masterTable("役職",masterPositions,"現在入力済みの役職マスターです。承認階層は詳細画面で管理します。");$("#jobMaster").onclick=()=>masterTable("職種",masterJobs,"現在入力済みの職種マスターです。");$("#groupMaster").onclick=()=>masterTable("担当グループ",["医療安全管理者"],"組織上の役職とは別の業務担当です。");$("#patternMaster").onclick=showPatternAdmin;$("#routeMaster").onclick=showRouteMaster}
function showDepartmentMaster(){content.innerHTML=head("所属","拠点を選択すると、その拠点に属する所属だけを表示します。",'<button id="addDept">＋所属追加</button>')+`<div class="card"><label>拠点<select id="siteFilter">${masterSites.map(s=>`<option>${s.name}</option>`).join("")}</select></label><div id="deptRows"></div></div>`;const draw=()=>{const site=$("#siteFilter").value,rows=masterDepartments.filter(d=>d.site===site);$("#deptRows").innerHTML=`<div class="table-wrap"><table><thead><tr><th>所属名</th><th>拠点</th><th>状態</th><th></th></tr></thead><tbody>${rows.map(d=>`<tr><td>${d.name}</td><td>${d.site}</td><td><span class="badge">有効</span></td><td><button class="secondary">編集</button> <button class="secondary">使用状況</button></td></tr>`).join("")}</tbody></table></div>`};$("#siteFilter").onchange=draw;draw();$("#addDept").onclick=()=>toast("所属追加（テスト）")}
function showStaffMaster(){content.innerHTML=head("職員管理","公開テストサイトのため実職員データは表示せず、登録画面の動作だけ確認できます。",'<button id="addStaff">＋職員追加</button>')+`<div class="notice">実運用では、氏名・氏名カナは分割せず管理します。拠点・所属・職種・役職は名称から選択します。</div><div class="card"><div class="grid2"><label>職員ID<input value="TEST-0001"></label><label>氏名<input value="テスト 職員"></label><label>氏名カナ<input value="テスト ショクイン"></label><label>拠点<select id="staffSite">${masterSites.map(s=>`<option>${s.name}</option>`).join("")}</select></label><label>所属<select id="staffDept"></select></label><label>職種<select>${masterJobs.map(x=>`<option>${x}</option>`).join("")}</select></label><label>役職<select><option>なし</option>${masterPositions.map(x=>`<option>${x}</option>`).join("")}</select></label><label>在籍状態<select><option>在籍</option><option>休職</option><option>退職</option></select></label></div><label class="inline"><input type="checkbox">システム管理者</label><div class="actions"><button id="saveStaffDemo">保存（テスト）</button></div></div>`;const sync=()=>{$("#staffDept").innerHTML=masterDepartments.filter(d=>d.site===$("#staffSite").value).map(d=>`<option>${d.name}</option>`).join("")};$("#staffSite").onchange=sync;sync();$("#saveStaffDemo").onclick=()=>toast("職員情報を保存しました（テスト）");$("#addStaff").onclick=()=>toast("新規職員登録画面として利用します")}
function showRouteMaster(){content.innerHTML=head("承認経路","申請者は経路を選択しません。条件により自動判定し、申請前に実経路を表示します。")+`<div class="card"><h2>経路作成イメージ</h2><div class="grid2"><label>申請書<select><option>時間外勤務申請</option></select></label><label>適用拠点<select><option>すべて</option>${masterSites.map(s=>`<option>${s.name}</option>`).join("")}</select></label><label>適用所属<select><option>すべて</option>${masterDepartments.map(d=>`<option>${d.site}｜${d.name}</option>`).join("")}</select></label></div></div><div class="card"><h2>承認STEP</h2><div class="route"><span>1</span><div><b>役職から選択</b><small>例：主任・師長・部長など</small></div><b>→</b><span>2</span><div><b>担当グループから選択</b><small>例：勤怠担当</small></div><b>→</b><span>3</span><div><b>個人から選択</b><small>必要な場合のみ</small></div></div><div class="notice" style="margin-top:14px">役職指定STEPでは、申請者の役職階層を考慮して下位STEPをスキップできる設計です。自己承認は禁止ルールにはしていません。</div><div class="actions"><button class="secondary" id="routeTest">経路テスト</button><button id="routeSave">保存（テスト）</button></div></div>`;$("#routeTest").onclick=()=>toast("職員を指定して実経路を確認する機能を実装予定");$("#routeSave").onclick=()=>toast("承認経路を保存しました（テスト）")}

/* v0.3.3: display-order and many-to-many work-pattern assignment UI */
function showDepartmentMaster(){content.innerHTML=head("所属","拠点を選択すると所属を絞り込めます。「すべて」で全拠点を一度に確認できます。",'<button id="addDept">＋所属追加</button>')+`<div class="card"><label>拠点<select id="siteFilter"><option>すべて</option>${masterSites.map(s=>`<option>${s.name}</option>`).join("")}</select></label><div id="deptRows"></div></div>`;const draw=()=>{const site=$("#siteFilter").value;let rows=masterDepartments.map((d,i)=>({...d,order:i+1}));if(site!=="すべて")rows=rows.filter(d=>d.site===site);$("#deptRows").innerHTML=`<div class="table-wrap"><table><thead><tr><th>表示順</th><th>所属名</th><th>拠点</th><th>状態</th><th></th></tr></thead><tbody>${rows.map(d=>`<tr><td><b>${d.order}</b></td><td>${d.name}</td><td>${d.site}</td><td><span class="badge">有効</span></td><td><button class="secondary">編集</button> <button class="secondary">使用状況</button></td></tr>`).join("")}</tbody></table></div>`};$("#siteFilter").onchange=draw;draw();$("#addDept").onclick=()=>toast("所属追加（テスト）")}
function orderedMasterTable(title,items,sub){content.innerHTML=head(title,sub,'<button id="addMaster">＋追加</button>')+`<div class="card table-wrap"><table><thead><tr><th>表示順</th><th>名称</th><th>状態</th><th></th></tr></thead><tbody>${items.map((x,i)=>`<tr><td><b>${i+1}</b></td><td>${typeof x==="string"?x:x.name}</td><td><span class="badge">有効</span></td><td><button class="secondary masterEdit">編集</button> <button class="secondary masterUse">使用状況</button></td></tr>`).join("")}</tbody></table></div>`;$("#addMaster").onclick=()=>toast("追加画面（テスト）");document.querySelectorAll(".masterEdit").forEach(b=>b.onclick=()=>toast("編集画面（テスト）"));document.querySelectorAll(".masterUse").forEach(b=>b.onclick=()=>toast("使用状況を確認（テスト）"))}
function showPatternAdmin(){const rows=[{name:"基本勤務",start:"09:00",end:"18:00",br:60,order:1,links:["TSOC北参道｜外来医事課","TSOC北参道｜放射線部","TSOC池袋｜外来医事課","TSOC池袋｜放射線部"]},{name:"早番",start:"08:30",end:"17:30",br:60,order:2,links:["TSOC北参道｜病棟看護部","TSOC北参道｜外来看護部"]},{name:"遅番",start:"10:00",end:"19:00",br:60,order:3,links:["TSOC北参道｜外来看護部","TSOC池袋｜外来看護部"]}];content.innerHTML=head("勤務パターン","勤務パターンは共通マスターとして1件作成し、複数の「拠点＋所属」へ紐づけます。多対多で管理します。",'<button id="addPattern">＋勤務パターン追加</button>')+`<div class="notice"><b>関係：</b> 1つの勤務パターン → 複数所属 ／ 1つの所属 → 複数勤務パターン。重複して同じ勤務パターンを作る必要はありません。</div><div class="card table-wrap"><table><thead><tr><th>表示順</th><th>勤務パターン</th><th>所定時間</th><th>休憩</th><th>利用所属数</th><th></th></tr></thead><tbody>${rows.map((p,i)=>`<tr><td><b>${p.order}</b></td><td>${p.name}</td><td>${p.start}～${p.end}</td><td>${p.br}分</td><td>${p.links.length}所属</td><td><button class="secondary patternDetail" data-i="${i}">紐づけ確認・編集</button></td></tr>`).join("")}</tbody></table></div><div id="patternDetail"></div>`;document.querySelectorAll(".patternDetail").forEach(b=>b.onclick=()=>{const p=rows[+b.dataset.i];$("#patternDetail").innerHTML=`<div class="card"><h2>${p.name}｜利用所属</h2><p class="muted">拠点＋所属を名称で選択します。内部コードは通常表示しません。</p>${p.links.map(x=>`<div class="dependency">${x} <button class="secondary" style="float:right">紐づけ解除</button></div>`).join("")}<div class="grid2"><label>拠点<select id="linkSite">${masterSites.map(s=>`<option>${s.name}</option>`).join("")}</select></label><label>所属<select id="linkDept"></select></label></div><div class="actions"><button id="addLink">＋この所属を追加</button></div></div>`;const sync=()=>$("#linkDept").innerHTML=masterDepartments.filter(d=>d.site===$("#linkSite").value).map(d=>`<option>${d.name}</option>`).join("");$("#linkSite").onchange=sync;sync();$("#addLink").onclick=()=>toast("勤務パターンと所属を紐づけました（テスト）")});$("#addPattern").onclick=()=>toast("勤務パターン追加（テスト）")}

const _showAdminV033=showAdmin;
showAdmin=function(){content.innerHTML=head("管理","名称中心で管理します。表示順を持つマスターは順位も画面に表示します。")+`<div class="admin-grid">
<div class="admin-tile"><b>職員管理</b><p class="muted">氏名、所属、職種、役職、権限</p><button id="staffMaster">確認</button></div>
<div class="admin-tile"><b>拠点</b><p class="muted">表示順を確認・管理</p><button id="siteMaster">確認</button></div>
<div class="admin-tile"><b>所属</b><p class="muted">全拠点表示／拠点別絞り込み</p><button id="deptMaster">確認</button></div>
<div class="admin-tile"><b>役職</b><p class="muted">表示順・承認階層</p><button id="positionMaster">確認</button></div>
<div class="admin-tile"><b>職種</b><p class="muted">表示順を確認・管理</p><button id="jobMaster">確認</button></div>
<div class="admin-tile"><b>担当グループ</b><p class="muted">業務上の役割・担当</p><button id="groupMaster">確認</button></div>
<div class="admin-tile"><b>勤務パターン</b><p class="muted">勤務パターン ⇔ 拠点＋所属を多対多で紐づけ</p><button id="patternMaster">確認</button></div>
<div class="admin-tile"><b>承認経路</b><p class="muted">個人・役職・担当グループを組合せ</p><button id="routeMaster">確認</button></div></div>`;
$("#staffMaster").onclick=showStaffMaster;$("#siteMaster").onclick=()=>orderedMasterTable("拠点",masterSites,"表示順の数字を画面上でも確認できます。");$("#deptMaster").onclick=showDepartmentMaster;$("#positionMaster").onclick=()=>orderedMasterTable("役職",masterPositions,"表示順に加えて、詳細画面では承認階層も管理します。");$("#jobMaster").onclick=()=>orderedMasterTable("職種",masterJobs,"表示順の数字を画面上でも確認できます。");$("#groupMaster").onclick=()=>masterTable("担当グループ",["医療安全管理者"],"組織上の役職とは別の業務担当です。");$("#patternMaster").onclick=showPatternAdmin;$("#routeMaster").onclick=showRouteMaster};

/* v0.3.4: compact work-pattern assignment UI */
function showPatternAdmin(){const rows=[{name:"基本勤務",start:"09:00",end:"18:00",br:60,order:1,links:["TSOC北参道｜外来医事課","TSOC北参道｜放射線部","TSOC池袋｜外来医事課","TSOC池袋｜放射線部"]},{name:"早番",start:"08:30",end:"17:30",br:60,order:2,links:["TSOC北参道｜病棟看護部","TSOC北参道｜外来看護部"]},{name:"遅番",start:"10:00",end:"19:00",br:60,order:3,links:["TSOC北参道｜外来看護部","TSOC池袋｜外来看護部"]}];content.innerHTML=head("勤務パターン","共通の勤務パターンと利用所属を多対多で管理します。",'<button id="addPattern">＋勤務パターン追加</button>')+`<div class="card table-wrap"><table><thead><tr><th>表示順</th><th>勤務パターン</th><th>所定時間</th><th>休憩</th><th>利用所属数</th><th></th></tr></thead><tbody>${rows.map((p,i)=>`<tr><td><b>${p.order}</b></td><td>${p.name}</td><td>${p.start}～${p.end}</td><td>${p.br}分</td><td>${p.links.length}所属</td><td><button class="secondary patternDetail" data-i="${i}">利用所属を設定</button></td></tr>`).join("")}</tbody></table></div><div id="patternDetail"></div>`;document.querySelectorAll(".patternDetail").forEach(b=>b.onclick=()=>{const p=rows[+b.dataset.i];$("#patternDetail").innerHTML=`<div class="card"><div class="page-head"><div><h2 style="margin:0">${p.name}｜利用所属</h2><div class="muted">現在 ${p.links.length} 所属で利用中</div></div></div><div class="table-wrap"><table><thead><tr><th>拠点</th><th>所属</th><th></th></tr></thead><tbody>${p.links.map(x=>{const a=x.split("｜");return `<tr><td>${a[0]}</td><td>${a[1]}</td><td><button class="linkbtn unlink">解除</button></td></tr>`}).join("")}</tbody></table></div><hr style="border:0;border-top:1px solid #e5eaf1;margin:22px 0"><h3>利用所属を追加</h3><div class="grid2"><label>拠点<select id="linkSite">${masterSites.map(s=>`<option>${s.name}</option>`).join("")}</select></label><label>所属<select id="linkDept"></select></label></div><div class="actions"><button id="addLink">＋追加</button></div></div>`;const sync=()=>$("#linkDept").innerHTML=masterDepartments.filter(d=>d.site===$("#linkSite").value).map(d=>`<option>${d.name}</option>`).join("");$("#linkSite").onchange=sync;sync();$("#addLink").onclick=()=>toast("利用所属を追加しました（テスト）");document.querySelectorAll(".unlink").forEach(x=>x.onclick=()=>toast("紐づけを解除しました（テスト）"))});$("#addPattern").onclick=()=>toast("勤務パターン追加（テスト）")}
